config/routes.rb
P16::Application.routes.draw do
  resources :bookings do
    collection { post :import }
  end

  resources :rooms do
    collection { post :import }
  end

resources :hosts do
    collection { post :import }
  end
  root :to=> 'hosts#index'

end

app/models/booking.rb
require 'csv'
class Booking < ActiveRecord::Base
  attr_accessible :end_date, :number_of_guests, :ref, :room_ref, :start_date

set_primary_key :ref
validates :ref, :presence=>true, :uniqueness=>true
belongs_to :room, :class_name=>"Room", :foreign_key=>"room_ref"


def self.import(file)

 # CSV.foreach(file.path) do |row|
additional_rows_to_skip = 1
 CSV.foreach(file.path) do |row|
 if additional_rows_to_skip > 0
additional_rows_to_skip-=1
else
 p = Booking.create!({
          :ref => row[0],
          :room_ref => row[1],
          :start_date => row[2],
	:end_date => row[2],
	:number_of_guests =>row[3],
        }
      )
  end
end

end

end

app/models/host.rb
require 'csv'
class Host < ActiveRecord::Base
  attr_accessible :address, :name, :ref
set_primary_key :ref
validates :ref, :presence=>true, :uniqueness=>true
has_many :rooms, :class_name=>"Room", :foreign_key=>'host_ref'

def self.import(file)

 # CSV.foreach(file.path) do |row|
additional_rows_to_skip = 1
 CSV.foreach(file.path) do |row|
 if additional_rows_to_skip > 0
additional_rows_to_skip-=1
else
 p = Host.create!({
          :ref => row[0],
          :name => row[1],
          :address => row[2],
        }
      )
  end
end
#Host.delete_all("ref='ref'")
end


  

end

app/models/room.rb
require 'csv'
class Room < ActiveRecord::Base
  attr_accessible :capacity, :host_ref, :ref

set_primary_key :ref
validates :ref, :presence=>true, :uniqueness=>true
belongs_to :host, :class_name=>"Host", :foreign_key=>"host_ref"
has_many :bookings, :class_name=>"Booking",:foreign_key=>'room_ref'


def self.import(file)

 # CSV.foreach(file.path) do |row|
additional_rows_to_skip = 1
 CSV.foreach(file.path) do |row|
 if additional_rows_to_skip > 0
additional_rows_to_skip-=1
else
 p = Room.create!({
          :ref => row[0],
          :host_ref => row[1],
          :capacity => row[2],
        }
      )
  end
end
#Host.delete_all("ref='ref'")
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bookings }
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @booking = Booking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @booking }
    end
  end

  # GET /bookings/new
  # GET /bookings/new.json
  def new
    @booking = Booking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @booking }
    end
  end

  # GET /bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(params[:booking])

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, :notice => 'Booking was successfully created.' }
        format.json { render :json => @booking, :status => :created, :location => @booking }
      else
        format.html { render :action => "new" }
        format.json { render :json => @booking.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bookings/1
  # PUT /bookings/1.json
  def update
    @booking = Booking.find(params[:id])

    respond_to do |format|
      if @booking.update_attributes(params[:booking])
        format.html { redirect_to @booking, :notice => 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @booking.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :no_content }
    end
  end

def import
  Booking.import(params[:file])
  redirect_to bookings_url, :notice=> "Bookings imported."
end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @hosts }
    end
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
    @host = Host.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @host }
    end
  end

  # GET /hosts/new
  # GET /hosts/new.json
  def new
    @host = Host.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @host }
    end
  end

  # GET /hosts/1/edit
  def edit
    @host = Host.find(params[:id])
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(params[:host])

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, :notice => 'Host was successfully created.' }
        format.json { render :json => @host, :status => :created, :location => @host }
      else
        format.html { render :action => "new" }
        format.json { render :json => @host.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hosts/1
  # PUT /hosts/1.json
  def update
    @host = Host.find(params[:id])

    respond_to do |format|
      if @host.update_attributes(params[:host])
        format.html { redirect_to @host, :notice => 'Host was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @host.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host = Host.find(params[:id])
    @host.destroy

    respond_to do |format|
      format.html { redirect_to hosts_url }
      format.json { head :no_content }
    end
  end

def import
  Host.import(params[:file])
  redirect_to hosts_url, :notice=> "Hosts imported."
end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, :notice => 'Room was successfully created.' }
        format.json { render :json => @room, :status => :created, :location => @room }
      else
        format.html { render :action => "new" }
        format.json { render :json => @room.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, :notice => 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @room.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end

def import
  Room.import(params[:file])
  redirect_to rooms_url, :notice=> "Rooms imported."
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ref %><br />
    <%= f.text_field :ref %>
  </div>
  <div class="field">
    <%= f.label :room_ref %><br />
    <%= f.text_field :room_ref %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :number_of_guests %><br />
    <%= f.number_field :number_of_guests %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Bookings</h1><br />

<%= link_to 'New Booking', new_booking_path %>



<h2>Import Bookings</h2>
<%= form_tag import_bookings_path, :multipart=> true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<br />
<h1>Listing bookings</h1>

<table>
  <tr>
    <th>Ref</th>
    <th>Room ref</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Number of guests</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookings.each do |booking| %>
  <tr>
    <td><%= booking.ref %></td>
    <td><%= booking.room_ref %></td>
    <td><%= booking.start_date %></td>
    <td><%= booking.end_date %></td>
    <td><%= booking.number_of_guests %></td>
    <td><%= link_to 'Show', booking %></td>
    <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
    <td><%= link_to 'Destroy', booking, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ref:</b>
  <%= @booking.ref %>
</p>

<p>
  <b>Room ref:</b>
  <%= @booking.room_ref %>
</p>

<p>
  <b>Start date:</b>
  <%= @booking.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @booking.end_date %>
</p>

<p>
  <b>Number of guests:</b>
  <%= @booking.number_of_guests %>
</p>


<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ref %><br />
    <%= f.text_field :ref %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hosts/edit.html.erb
<h1>Editing host</h1>

<%= render 'form' %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<h1>Hosts</h1><br />

<%= link_to 'New Host', new_host_path %><br />



<h2>Import Hosts</h2>
<%= form_tag import_hosts_path, :multipart=> true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<br />
<h1>Listing hosts</h1>

<table>
  <tr>
    <th>Ref</th>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hosts.each do |host| %>
  <tr>
    <td><%= host.ref %></td>
    <td><%= host.name %></td>
    <td><%= host.address %></td>
    <td><%= link_to 'Show', host %></td>
    <td><%= link_to 'Edit', edit_host_path(host) %></td>
    <td><%= link_to 'Destroy', host, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/hosts/new.html.erb
<h1>New host</h1>

<%= render 'form' %>

<%= link_to 'Back', hosts_path %>

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ref:</b>
  <%= @host.ref %>
</p>

<p>
  <b>Name:</b>
  <%= @host.name %>
</p>

<p>
  <b>Address:</b>
  <%= @host.address %>
</p>


<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P16</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ref %><br />
    <%= f.text_field :ref %>
  </div>
  <div class="field">
    <%= f.label :host_ref %><br />
    <%= f.text_field :host_ref %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.number_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing rooms</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Rooms</h1><br />

<%= link_to 'New Room', new_room_path %>



<h2>Import Rooms</h2>
<%= form_tag import_rooms_path, :multipart=> true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<br />
<h1>Listing rooms</h1>


<table>
  <tr>
    <th>Ref</th>
    <th>Host ref</th>
    <th>Capacity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.ref %></td>
    <td><%= room.host_ref %></td>
    <td><%= room.capacity %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ref:</b>
  <%= @room.ref %>
</p>

<p>
  <b>Host ref:</b>
  <%= @room.host_ref %>
</p>

<p>
  <b>Capacity:</b>
  <%= @room.capacity %>
</p>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>